# -*- coding: utf-8 -*-
"""encode_decode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ExEnXWoXNOrg6jD8CSuY-UfZ0oEOVku
"""

# korean(Hangul) to ASKII code by encoding utf-8
ko="안녕하세요".encode('utf-8')
print(ko)

# Tranditional Chinese to ASKII code by encoding utf-8
tw="你好".encode('utf-8')
print(tw)

# Recover to orininal character by decoding utf-8
print(ko.decode('utf-8'), tw.decode('utf-8'))